// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    [Migration("20260526133757_AddImageUrlSeeding")]
    partial class AddImageUrlSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Auction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Auctions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Apple MacBook Pro 13 tum, 16GB RAM, 512GB SSD",
                            EndDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://localhost:7140/macbook.jpg",
                            IsActive = true,
                            Price = 8000m,
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "MacBook Pro 2020",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "Apple iPhone 13 Pro 256GB, Pacific Blue",
                            EndDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://localhost:7140/iphone.jpg",
                            IsActive = true,
                            Price = 5000m,
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "iPhone 13 Pro",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "RTX 3080, Intel i9, 32GB RAM, 1TB SSD",
                            EndDate = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://localhost:7140/gaming-pc.jpg",
                            IsActive = true,
                            Price = 15000m,
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gaming PC",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "PS5 med två handkontroller och 5 spel",
                            EndDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://localhost:7140/ps5.jpg",
                            IsActive = true,
                            Price = 6000m,
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sony PlayStation 5",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Apple iPad Pro 12.9 tum, 256GB, WiFi + Cellular",
                            EndDate = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://localhost:7140/ipad.jpg",
                            IsActive = true,
                            Price = 9000m,
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "iPad Pro 12.9",
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "Samsung 32 tum 4K UHD monitor, 144Hz",
                            EndDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://localhost:7140/monitor.jpg",
                            IsActive = true,
                            Price = 4000m,
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Samsung 4K Monitor",
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "DJI Mavic Air 2, 4K kamera, 34 min flygtid",
                            EndDate = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://localhost:7140/drone.jpg",
                            IsActive = true,
                            Price = 7000m,
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "DJI Drone",
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            Description = "Corsair K95 RGB, Cherry MX switches",
                            EndDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://localhost:7140/keyboard.jpg",
                            IsActive = true,
                            Price = 1500m,
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mechanical Keyboard",
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "Nintendo Switch OLED med 10 spel",
                            EndDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://localhost:7140/nintendo.jpg",
                            IsActive = true,
                            Price = 3500m,
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Nintendo Switch OLED",
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            Description = "Apple Watch Series 7, 45mm, Midnight",
                            EndDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://localhost:7140/applewatch.jpg",
                            IsActive = true,
                            Price = 4500m,
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Apple Watch Series 7",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Domain.Entities.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BidTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.ToTable("Bids");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1200.00m,
                            AuctionId = 1,
                            BidTime = new DateTime(2026, 5, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1500.00m,
                            AuctionId = 1,
                            BidTime = new DateTime(2026, 5, 10, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1700.00m,
                            AuctionId = 1,
                            BidTime = new DateTime(2026, 5, 11, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            Amount = 2000.00m,
                            AuctionId = 1,
                            BidTime = new DateTime(2026, 5, 11, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            Amount = 500.00m,
                            AuctionId = 2,
                            BidTime = new DateTime(2026, 5, 12, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            Amount = 650.00m,
                            AuctionId = 2,
                            BidTime = new DateTime(2026, 5, 12, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            Id = 7,
                            Amount = 800.00m,
                            AuctionId = 2,
                            BidTime = new DateTime(2026, 5, 12, 16, 20, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            Amount = 10000.00m,
                            AuctionId = 3,
                            BidTime = new DateTime(2026, 5, 13, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 5
                        },
                        new
                        {
                            Id = 9,
                            Amount = 11000.00m,
                            AuctionId = 3,
                            BidTime = new DateTime(2026, 5, 13, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            Id = 10,
                            Amount = 12500.00m,
                            AuctionId = 3,
                            BidTime = new DateTime(2026, 5, 14, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@auction.com",
                            IsActive = true,
                            Name = "Admin",
                            PasswordHash = "$2a$12$k.CAYoiBFeMKOU6wVgeH6eMLtrVlynJBz/kTM1eGAcSkMn3W5WjsO",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "anna@gmail.com",
                            IsActive = true,
                            Name = "Anna Svensson",
                            PasswordHash = "$2a$12$socZ4WBBbqi8WOHeAL5PE.sZo5l9/Z/q2KYID5zp1E6TGg6JCcRh6",
                            Role = "user"
                        },
                        new
                        {
                            Id = 3,
                            Email = "suthida@hotmail.com",
                            IsActive = true,
                            Name = "Suthida Damchum",
                            PasswordHash = "$2a$12$i5PUbFxSc6N7QH1WAHt1i.1S7RVcafYAWiyG36xG42LnCU917dJP",
                            Role = "user"
                        },
                        new
                        {
                            Id = 4,
                            Email = "rasmus@hotmail.com",
                            IsActive = true,
                            Name = "Rasmus Back",
                            PasswordHash = "$2a$12$WQ3NsQgOPjctZwvk/dJu8emIZXV57JWUN0uD.QCYgqsFjneNk7uwG",
                            Role = "user"
                        },
                        new
                        {
                            Id = 5,
                            Email = "amanda@hotmail.com",
                            IsActive = true,
                            Name = "Amanda Park",
                            PasswordHash = "$2a$12$MdZbX9THP5GtTJ/7lEJpcOLComityiZK7FejdUWiRCh1QhCmow4v",
                            Role = "user"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Auction", b =>
                {
                    b.HasOne("Domain.Entities.User", "CreatedBy")
                        .WithMany("Auctions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Domain.Entities.Bid", b =>
                {
                    b.HasOne("Domain.Entities.Auction", null)
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Auction", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Auctions");
                });
#pragma warning restore 612, 618
        }
    }
}
